name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ""  # Sin contraseña (opcional)
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Permitir contraseña vacía
          MYSQL_DATABASE: devstagram  # Nombre de la base de datos
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          mysql -h 127.0.0.1 -P 3306 -u root -e "SHOW DATABASES;" && break || sleep 1
        done
    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: devstagram  # Nombre de la base de datos
        DB_USERNAME: root
        DB_PASSWORD: ""  # Sin contraseña (opcional)
      run: php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: devstagram  # Nombre de la base de datos
        DB_USERNAME: root
        DB_PASSWORD: ""  # Sin contraseña (opcional)
      run: php artisan test
