name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Configura PHP para la ejecución de tests en Laravel
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          
      # Clona el repositorio
      - uses: actions/checkout@v4

      # Crea el archivo .env basado en .env.example
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Instala dependencias de Composer
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Genera la clave de aplicación
      - name: Generate key
        run: php artisan key:generate

      # Ajusta los permisos de las carpetas
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # Crea una base de datos SQLite para pruebas
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      # Ejecuta las migraciones
      - name: Run migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --env=testing

      # Ejecuta pruebas de PHPUnit o Pest
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
